stages:
  - build
  - deploy

build:
  stage: build
  image: px4io/px4-dev-nuttx-bionic:2021-12-11
  script:
    - make modalai_fc-v2_bootloader
    - make modalai_fc-v2
  only:
    - bright-1.13.2
  artifacts:
    untracked: true
    expire_in: 20 min

deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - BUILD=$(git describe --tags)
    - DATE=$(date +"%Y-%m-%d--%H-%M")
    - BUILD_DIR=$DATE-$BUILD
    - GCLOUD_BUCKET=gs://modalai_public/flightcore-builds/FPV-v1.13/$BUILD_DIR
    - gcloud auth activate-service-account --key-file=$GCLOUD_SERVICE_KEY
    - gsutil cp build/modalai_fc-v2_default/modalai_fc-v2_default.bin $GCLOUD_BUCKET/fc-v2/app/
    - gsutil cp build/modalai_fc-v2_default/modalai_fc-v2_default.px4 $GCLOUD_BUCKET/fc-v2/app/
    - gsutil cp build/modalai_fc-v2_bootloader/modalai_fc-v2_bootloader.bin $GCLOUD_BUCKET/fc-v2/bl/
    - gsutil cp build/modalai_fc-v2_bootloader/modalai_fc-v2_bootloader.px4 $GCLOUD_BUCKET/fc-v2/bl/
  only:
    - bright-1.13.2
